# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtWidgets
import sys

app = QtWidgets.QApplication(sys.argv)
screen  = app.primaryScreen()
width = screen.size().width()
height = screen.size().height()

print("Width screen : ", width)
print("Height screen : ", height)

print("Number of int in width : ", len(str(width)))
print("Number of int in height : ", len(str(height)))