# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'V1QUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
   
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(951, 723)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(40, 20, 191, 20))
        self.label.setObjectName("label")
        self.comboBox = QtWidgets.QComboBox(Form)
        self.comboBox.setGeometry(QtCore.QRect(50, 40, 161, 22))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.spinBox = QtWidgets.QSpinBox(Form)
        self.spinBox.setGeometry(QtCore.QRect(200, 80, 42, 22))
        self.spinBox.setMinimum(5)
        self.spinBox.setObjectName("spinBox")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(20, 80, 181, 21))
        self.label_2.setObjectName("label_2")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(20, 110, 181, 21))
        self.label_4.setObjectName("label_4")
        self.spinBox_2 = QtWidgets.QSpinBox(Form)
        self.spinBox_2.setGeometry(QtCore.QRect(200, 110, 42, 22))
        self.spinBox_2.setMinimum(5)
        self.spinBox_2.setObjectName("spinBox_2")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(90, 150, 91, 51))
        self.pushButton.setObjectName("pushButton")
        self.pushButton.clicked.connect(self.click)
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setGeometry(QtCore.QRect(260, 0, 691, 721))
        self.widget.setObjectName("widget")
        
        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)
    
    def click(self) :    
         paint = QtGui.QPainter(self.widget)
         paint.drawRect(500,200,50,50)
         print("pressed")    
        
    def paintEvent(self, event):             # event de type QPaintEvent
        painter = QtGui.QPainter(self.widget)             # recupere le QPainter du widget
        painter.drawRect(5,5,120,40)         # dessiner un rectangle noir
        return   
        
        
    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Veuillez choisir le polygone à dessiner :"))
        self.comboBox.setItemText(0, _translate("Form", "Triangle"))
        self.comboBox.setItemText(1, _translate("Form", "Carré"))
        self.comboBox.setItemText(2, _translate("Form", "Hexagone"))
        self.label_2.setText(_translate("Form", "Nombre de polygone en horizontal : "))
        self.label_4.setText(_translate("Form", "Nombre de polygone en vertical : "))
        self.pushButton.setText(_translate("Form", "Déssiner"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
